title: Sebastian Annies
description: > # isoparser mp4parser mpeg-dash common encryption isobmff java spring servlet python django
  html http websocket rest json xml protobuf widevine playready DRM
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.sebastian-annies.de" # the base hostname & protocol for your site

# User setting
owner: Sebastian Annies
email: sannies@sebastian-annies.de
facebook_username:
twitter_username:
github_username: sannies
address:
  - line: Hellkamp 58
  - line: 20255 Hamburg
  # Feel free to add more lines here
telephone: (+49) 174 9 25 26 10 / (+27) 81 275 18 72
copyright:

# API settings
google_api_key: AIzaSyDW0pFjEhPKjtTIBxobWb9wpnpzRjKGZ6I

# Build settings
markdown: kramdown
